{"uuid": "068fc0b9-09b1-40e6-a6a8-88210afbecfe", "children": ["fe0aea32-f268-4b9a-b485-8b91530ff1ba"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom no such execution context: uniqueContextId not found\n  (Session info: chrome=115.0.5790.170)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0112A813+48355]\n\t(No symbol) [0x010BC4B1]\n\t(No symbol) [0x00FC5358]\n\t(No symbol) [0x00FB89B0]\n\t(No symbol) [0x00FB7138]\n\t(No symbol) [0x00FB77AA]\n\t(No symbol) [0x00FC8417]\n\t(No symbol) [0x00FC99E1]\n\t(No symbol) [0x00FC9A80]\n\t(No symbol) [0x01011F1B]\n\t(No symbol) [0x0101093C]\n\t(No symbol) [0x0100A536]\n\t(No symbol) [0x00FE82DC]\n\t(No symbol) [0x00FE93DD]\n\tGetHandleVerifier [0x0138AABD+2539405]\n\tGetHandleVerifier [0x013CA78F+2800735]\n\tGetHandleVerifier [0x013C456C+2775612]\n\tGetHandleVerifier [0x011B51E0+616112]\n\t(No symbol) [0x010C5F8C]\n\t(No symbol) [0x010C2328]\n\t(No symbol) [0x010C240B]\n\t(No symbol) [0x010B4FF7]\n\tBaseThreadInitThunk [0x766E7D59+25]\n\tRtlInitializeExceptionChain [0x7715B79B+107]\n\tRtlClearBits [0x7715B71F+191]\n\n", "trace": "  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\Desktop\\SW Testing\\Pytest framework\\CredKart_pytest_project 31-07-2023\\CredKart_Pytest_Project - Copy\\testCases\\conftest.py\", line 36, in setup\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 54, in __init__\n    super().__init__(\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691424662156, "stop": 1691424669471}], "start": 1691424662156, "stop": 1691424669653}