{"uuid": "ed9f680f-9b0e-4e06-ad5c-a1d6fcc05467", "children": ["e960446f-253e-479b-a343-0c4f15b34f48"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=115.0.5790.170)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0112A813+48355]\n\t(No symbol) [0x010BC4B1]\n\t(No symbol) [0x00FC5358]\n\t(No symbol) [0x00FC1B33]\n\t(No symbol) [0x00FB8CA5]\n\t(No symbol) [0x00FB9D0A]\n\t(No symbol) [0x00FB9003]\n\t(No symbol) [0x00FB8355]\n\t(No symbol) [0x00FB82EC]\n\t(No symbol) [0x00FB6F26]\n\t(No symbol) [0x00FB7688]\n\t(No symbol) [0x00FC6B52]\n\t(No symbol) [0x0101CF01]\n\t(No symbol) [0x0100A73C]\n\t(No symbol) [0x0101C922]\n\t(No symbol) [0x0100A536]\n\t(No symbol) [0x00FE82DC]\n\t(No symbol) [0x00FE93DD]\n\tGetHandleVerifier [0x0138AABD+2539405]\n\tGetHandleVerifier [0x013CA78F+2800735]\n\tGetHandleVerifier [0x013C456C+2775612]\n\tGetHandleVerifier [0x011B51E0+616112]\n\t(No symbol) [0x010C5F8C]\n\t(No symbol) [0x010C2328]\n\t(No symbol) [0x010C240B]\n\t(No symbol) [0x010B4FF7]\n\tBaseThreadInitThunk [0x766E7D59+25]\n\tRtlInitializeExceptionChain [0x7715B79B+107]\n\tRtlClearBits [0x7715B71F+191]\n\n", "trace": "  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\makde\\Desktop\\SW Testing\\Pytest framework\\CredKart_pytest_project 31-07-2023\\CredKart_Pytest_Project - Copy\\testCases\\conftest.py\", line 38, in setup\n    driver.get(\"https://automation.credence.in\")\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\makde\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691424670601, "stop": 1691424680613}], "start": 1691424670601, "stop": 1691424683217}